export const COLORS : { [key: string]: string[] }  = {
  'Python': ['bg-[#3572a5]', 'text-white'],
  'JavaScript': ['bg-[#f1e05a]', 'text-black'],
  'TypeScript': ['bg-[#2b7489]', 'text-white'],
  'HTML': ['bg-[#e34c26]', 'text-white'],
  'CSS': ['bg-[#563d7c]', 'text-white'],
  'React.js': ['bg-[#61dafb]', 'text-black'],
  'Node.js': ['bg-[#026e00]', 'text-white'],
  'Express.js': ['bg-[#000000]', 'text-white'],
  'Django': ['bg-[#092e20]', 'text-white'],
  'Flask': ['bg-[#000000]', 'text-white'],
  'React Native': ['bg-[#61dafb]', 'text-black'],
  'FastAPI': ['bg-[#009688]', 'text-white'],
  'Django REST framework': ['bg-[#092e20]', 'text-white'],
  'Tailwind': ['bg-[#38B2AC]', 'text-black'],
  'Next.js': ['bg-[#000000]', 'text-white'],
  'DinamoDB': ['bg-[#4053D6]', 'text-white'],
  'GraphQL': ['bg-[#E10098]', 'text-white'],
  'PostgreSQL': ['bg-[#336791]', 'text-white'],
  'Git': ['bg-[#F05032]', 'text-white'],
  'Docker': ['bg-[#2496ED]', 'text-white'],
  'AWS': ['bg-[#FF9900]', 'text-black'],
  'Snowflake': ['bg-[#269539]', 'text-white'],
  'Jquery': ['bg-[#0769AD]', 'text-white'],
}